---
# tasks file for podman

- name: assert supported distributions and versions
  assert:
    that:
      - ( ansible_distribution == "RedHat" and ( ansible_distribution_version >= '7.8' )
        ) or
        ( ansible_distribution == "CentOS" and ( ansible_distribution_version >= '7.8' )
        ) or
        ( ansible_distribution == "Fedora" and ( ansible_distribution_major_version == "31" )
        ) or
        ( ansible_distribution == "Debian" and ( ansible_distribution_major_version == "10" )
        ) or
        ( ansible_distribution == "Ubuntu" and ( ansible_distribution_major_version == "18" )
        )
    fail_msg: "Unsupported OS version: {{ ansible_os_family }} {{ ansible_distribution_version }}"


- name: include os specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution }}.yml"
      skip: true
  tags: vars

- include: install.yml
- include: template.yml
- include: configure.yml
